# Generated by Django 2.2.2 on 2019-06-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogscraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogpost',
            unique_together={('url', 'title', 'text')},
        ),
    ]
