# Generated by Django 2.2.2 on 2019-06-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogscraper', '0002_auto_20190613_1701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogpost',
            unique_together={('url', 'title')},
        ),
    ]
