# Generated by Django 2.2.2 on 2019-06-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogscraper', '0003_auto_20190613_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blogscraper.Author'),
        ),
        migrations.AlterUniqueTogether(
            name='blogpost',
            unique_together=set(),
        ),
    ]
