# Generated by Django 2.2.2 on 2019-06-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogscraper', '0004_auto_20190613_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='url',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
